Repository Vactor0911/wanna-trip, pull requests merged in 2024-11, with the labels that each got.

#1 Costar
  src/App.tsx
  src/assets/images/image01.png
  src/index.css
  src/pages/Day.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Plan.tsx
  src/pages/Register.tsx
  src/pages/Template.tsx
Labels: 개선

#12 costar 브랜치 백업 작업
  README.md
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Template.tsx
Labels: 오류 의심

#13 costar 브랜치 복구 작업
  src/pages/Register.tsx
  src/pages/Template.tsx
Labels: 오류 의심

#15 Jsukhen backup
  .github/ISSUE_TEMPLATE/문서화-보고서.md
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/오류-보고서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
  src/App.tsx
  src/assets/images/google.png
  src/assets/images/naver.png
  src/pages/Day.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/Template.tsx
Labels: 오류 의심

#16 Jsukhen
  .github/ISSUE_TEMPLATE/문서화-보고서.md
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/오류-보고서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
  src/App.tsx
  src/assets/images/google.png
  src/assets/images/naver.png
  src/pages/Day.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/Template.tsx
Labels: 개선

#18 프론트엔드 브랜치 합병 및 리팩토링
  .github/ISSUE_TEMPLATE/문서화-보고서.md
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/오류-보고서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/google.png
  src/assets/images/naver.png
  src/components/Card.tsx
  src/components/Content.tsx
  src/components/LoginButton.tsx
  src/pages/Day.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/NewTemplate.tsx
  src/pages/Plan.tsx
  src/pages/Register.tsx
  src/pages/Template.tsx
Labels: 개선

#29 Hits
  .gitignore
  package-lock.json
  package.json
  src/assets/images/background.png
  src/assets/images/kakao.png
  src/pages/Login.tsx
  src/pages/NewTemplate.tsx
  src/pages/Register.tsx
  src/state/index.ts
Labels: 개선

#31 Jsukhen
  src/assets/images/background.png
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Register.tsx
Labels: 개선

#33 Hits
  src/pages/Login.tsx
  src/pages/NewTemplate.tsx
  src/pages/Register.tsx
Labels: 개선

#35 카카오 간편 로그인 버그 해결
  src/pages/Login.tsx
  src/pages/NewTemplate.tsx
  src/pages/Register.tsx
Labels: 개선

#36 템플릿 페이지에 로그인 상태의 컴포넌트 추가
  src/components/LoginButton.tsx
  src/pages/NewTemplate.tsx
Labels: 개선

#37 costar
  src/components/Card.tsx
  src/pages/NewTemplate.tsx
Labels: 개선

#38 Jsukhen
  src/App.tsx
  src/components/Card.tsx
  src/components/Content.tsx
  src/pages/NewTemplate.tsx
  src/pages/Template.tsx
Labels: 개선

#39 일반, 카카오, 구글 로그인, 로그아웃 최종 구현 및 네이버 제거
  index.html
  package-lock.json
  package.json
  src/pages/Login.tsx
  src/pages/NewTemplate.tsx
  src/state/index.ts
Labels: 개선

#40 README.md 내용 수정
  README.md
Labels: 문서화

#44 Jsukhen
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: 개선
