Repository Vactor0911/wanna-trip, pull requests merged in 2025-05, with the labels that each got.

#105 프로젝트 최적화 및 오류 수정
  src/App.tsx
  src/components/TokenRefresher.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/Template.tsx
  src/state/index.ts
  src/utils/axiosInstance.ts
  vite.config.ts
Labels: 버그, 개선

#107 로그인 및 회원가입 페이지 재구현
  src/components/Header.tsx
  src/components/LoginButton.tsx
  src/components/MyButton.tsx
  src/components/MyIconButton.tsx
  src/components/OutlinedTextField.tsx
  src/components/PlainLinkProps.tsx
  src/components/Popups.tsx
  src/components/SectionHeader.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: 개선

#108 로그인 및 회원가입 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header.tsx
  src/components/LoginButton.tsx
  src/components/MyButton.tsx
  src/components/MyIconButton.tsx
  src/components/OutlinedTextField.tsx
  src/components/PlainLinkProps.tsx
  src/components/Popups.tsx
  src/components/SectionHeader.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Register.tsx
Labels: 개선

#109 템플릿 페이지 구현
  src/App.tsx
  src/assets/images/main1.png
  src/assets/images/main2.png
  src/components/Board.tsx
  src/components/Card.tsx
  src/components/Dialogs.tsx
  src/components/Header.tsx
  src/components/Tooltip.tsx
  src/pages/Main.tsx
  src/pages/Template.tsx
  src/state/index.ts
  src/utils/index.ts
  src/utils/template.ts
  src/utils/theme.ts
Labels: 개선

#110 페이지 및 컴포넌트 스타일 수정
  src/components/Board.tsx
  src/components/Header.tsx
  src/components/OutlinedTextField.tsx
  src/components/SectionHeader.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Register.tsx
  src/pages/Template.tsx
  src/utils/theme.ts
Labels: 개선

#111 메인, 로그인, 회원가입, 템플릿 페이지 구현
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/main1.png
  src/assets/images/main2.png
  src/components/Board.tsx
  src/components/Card.tsx
  src/components/Dialogs.tsx
  src/components/Header.tsx
  src/components/LoginButton.tsx
  src/components/MyButton.tsx
  src/components/MyIconButton.tsx
  src/components/OutlinedTextField.tsx
  src/components/PlainLinkProps.tsx
  src/components/Popups.tsx
  src/components/SectionHeader.tsx
  src/components/TokenRefresher.tsx
  src/components/Tooltip.tsx
  src/index.css
  src/main.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Register.tsx
  src/pages/Template.tsx
  src/pages/index.ts
  src/state/index.ts
  src/utils/axiosInstance.ts
  src/utils/index.ts
  src/utils/template.ts
  src/utils/theme.ts
  tsconfig.app.json
  vite.config.ts
Labels: 개선

#113 Hits
  src/components/Header.tsx
  src/components/TokenRefresher.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/utils/index.ts
  src/utils/loginUtils.ts
Labels: 개선

#114 Dev
  src/components/Header.tsx
  src/components/TokenRefresher.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/utils/index.ts
  src/utils/loginUtils.ts
Labels: 개선

#115 아이디 찾기, 비밀번호 찾기, 비밀번호 변경 페이지 추가
  src/App.tsx
  src/components/Header.tsx
  src/components/OutlinedTextField.tsx
  src/components/SquareTemplateCard.tsx
  src/pages/ChangePassword.tsx
  src/pages/Community.tsx
  src/pages/FindPassword.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/index.ts
  src/utils/theme.ts
Labels: 개선

#116 라우터 및 페이지 스타일 최적화
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-tasks.yml
  .github/ISSUE_TEMPLATE/문서화-보고서.md
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/오류-보고서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
  .github/React + Typescript + Vite.md
  src/App.tsx
  src/pages/Main.tsx
Labels: 개선

#117 새로운 페이지 구현 및 기존 코드 리팩토링
  src/App.tsx
  src/components/Header.tsx
  src/components/OutlinedTextField.tsx
  src/components/SquareTemplateCard.tsx
  src/pages/ChangePassword.tsx
  src/pages/Community.tsx
  src/pages/FindPassword.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Register.tsx
  src/pages/index.ts
  src/utils/theme.ts
Labels: 개선

#118 GitHub Pages 배포 workflow에 권한 속성 추가
  .github/workflows/deploy.yml
Labels: 버그

#119 Template test
  src/App.tsx
  src/components/Header.tsx
  src/components/SquareTemplateCard.tsx
  src/pages/Community.tsx
  src/pages/Login.tsx
  src/pages/Template.tsx
  src/pages/UserTemplates.tsx
  src/pages/index.ts
Labels: 개선

#120 Dev
  src/App.tsx
  src/components/Header.tsx
  src/components/SquareTemplateCard.tsx
  src/pages/Community.tsx
  src/pages/Login.tsx
  src/pages/Template.tsx
  src/pages/UserTemplates.tsx
  src/pages/index.ts
Labels: 개선

#121 Hits
  .github/workflows/deploy.yml
  src/App.tsx
Labels: 개선

#122 Dev
  src/App.tsx
Labels: 개선

#124 눈 아이콘 조건 수정
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: 개선

#125 인터셉터에 429 오류 처리 조건 추가
  src/utils/axiosInstance.ts
Labels: 개선
