Repository Vactor0911/wanna-trip, pull requests merged in 2025-03, with the labels that each got.

#88 프로젝트 1차 마무리
  .github/workflows/deploy.yml
  README.md
  package-lock.json
  package.json
  src/components/Board.tsx
  src/components/Card.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/Register.tsx
  src/pages/Template.tsx
  src/state/index.ts
Labels: 개선

#89 Main 페이지 리팩토링
  package-lock.json
  src/App.tsx
  src/pages/Main.tsx
  src/utils/index.ts
  vite.config.ts
Labels: 개선

#90 Dev
  package-lock.json
  src/App.tsx
  src/pages/Main.tsx
  src/utils/index.ts
  vite.config.ts
Labels: 개선

#92 이슈 템플릿 업데이트
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-tasks.yml
  .github/ISSUE_TEMPLATE/문서화-보고서.md
  .github/ISSUE_TEMPLATE/신규-기능-제안서.md
  .github/ISSUE_TEMPLATE/오류-보고서.md
  .github/ISSUE_TEMPLATE/작업-계획서.md
  .github/React + Typescript + Vite.md
Labels: 문서화

#93 페이지 리팩토링
  src/App.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: 개선

#94 페이지 리팩토링
  src/App.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: 개선

#95 카카오 간편 로그인 수정
  src/pages/Login.tsx
Labels: 개선

#96 카카오톡 간편 로그인 수정
  src/pages/Login.tsx
Labels: 버그
